content: |-
  {{ .Header }}

  ## Usage

  Create a Flink Application using AWS Kinesis Analytics.

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  Please see the [basic example](examples/basic) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
